import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import numpy as np
import glasbey
import pandas as pd
import tifffile
import plotly.graph_objects as go
import re
import warnings
from joblib import Parallel, delayed
from skimage.measure import block_reduce
from skimage.transform import resize
import plotly.express as px


CONSTRUCT_CHANNEL_ORDER = [
    "FLAG",
    "HA",
    "V5",
    "T7",
    "VSV-G",
    "AU1",
    "Myc",
    "S-tag",
    "HSV",
]

CHANNEL_ALIASES = {
    # Construct/tag names
    "dna": "DNA",
    "dapi": "DNA",
    "spy700": "DNA",
    "flag": "FLAG",
    "ha": "HA",
    "v5": "V5",
    "sv5": "V5",
    "t7": "T7",
    "vsvg": "VSV-G",
    "vsvgtag": "VSV-G",
    "au1": "AU1",
    "myc": "Myc",
    "stag": "S-tag",
    "hsv": "HSV",
    # Fluorophore aliases
    "dy549": "FLAG",
    "af532": "HA",
    "cf405m": "V5",
    "af405": "T7",
    "af660": "VSV-G",
    "af647": "AU1",
    "af594": "Myc",
    "af568": "S-tag",
    "af488": "HSV",
}


def _normalize_channel_name(name) -> str:
    return "".join(ch for ch in str(name).strip().lower() if ch.isalnum())


def _channel_name_tokens(name):
    return [tok for tok in re.split(r"[^0-9a-zA-Z]+", str(name).lower()) if tok]


def _canonical_construct_channel(name):
    normalized = _normalize_channel_name(name)
    direct = CHANNEL_ALIASES.get(normalized)
    if direct is not None:
        return direct

    for token in _channel_name_tokens(name):
        canonical = CHANNEL_ALIASES.get(token)
        if canonical is not None:
            return canonical

    return None


def _channel_match_token(name):
    canonical = _canonical_construct_channel(name)
    if canonical is not None:
        return f"canonical:{canonical}"
    return f"raw:{_normalize_channel_name(name)}"


def _infer_channel_count(metadata: dict, img: np.ndarray):
    channels = metadata.get("channels")
    if channels is not None:
        try:
            channels = int(channels)
        except (TypeError, ValueError):
            channels = None

    if channels is None:
        if img.ndim >= 4:
            channels = img.shape[1]
        elif img.ndim == 3:
            channels = img.shape[0]
        elif img.ndim == 2:
            channels = 1

    return channels


def _sanitize_labels(labels, channel_count):
    if labels is None:
        return None

    labels = list(labels)
    if channel_count is not None and len(labels) > channel_count:
        # Prevent excessive empty labels from being included - which can sometimes get generated by mistake.
        labels = labels[:channel_count]

    return labels


def read_tiff_with_tifffile(
    file_path,
    tags=None,
    include_nontags: bool = True,
    order_mode: str = "construct",
):
    """
    Read a TIFF and optionally reorder/filter channels.

    Args:
        file_path: TIFF path.
        tags: Channel names supplied by the caller.
        include_nontags: Keep channels not recognized as construct/barcoding channels.
        order_mode: "construct" (default), "fluorophore" (alias for construct),
            or "provided".
            - "construct": order by canonical construct order (DNA/FLAG/HA/V5/T7/...)
              while recognizing both fluorophore names and construct tags.
            - "provided": keep the channel order exactly as provided in `tags`.
    """
    valid_modes = {"construct", "fluorophore", "provided"}
    if order_mode not in valid_modes:
        raise ValueError(
            f"order_mode must be one of {sorted(valid_modes)}, got '{order_mode}'."
        )
    if order_mode == "fluorophore":
        order_mode = "construct"

    try:
        with tifffile.TiffFile(file_path) as tif:
            img = tif.asarray()
            metadata = tif.imagej_metadata or {}
            labels = _sanitize_labels(
                metadata.get("Labels", None),
                _infer_channel_count(metadata, img),
            )
            print(f"TIFF metadata labels: {labels}")
            print(f"Provided tags: {tags}")

            if len(img.shape) < 4:
                img = img[None]
            n_channels = img.shape[1]

            if tags is not None:
                tags = list(tags)
                if len(tags) > n_channels:
                    raise ValueError(
                        f"Received {len(tags)} tags, but image only has {n_channels} channels."
                    )

            channel_names = None
            if tags is not None:
                if len(tags) == n_channels:
                    # User-provided names are positional and should win.
                    channel_names = tags
                    if labels is not None and len(labels) >= n_channels:
                        mismatches = []
                        for idx, (tag, label) in enumerate(zip(tags, labels[:n_channels])):
                            if _channel_match_token(tag) != _channel_match_token(label):
                                mismatches.append((idx + 1, tag, label))

                        if mismatches:
                            preview_count = 5
                            mismatch_preview = ", ".join(
                                f"{idx}: tag='{tag}' vs label='{label}'"
                                for idx, tag, label in mismatches[:preview_count]
                            )
                            if len(mismatches) > preview_count:
                                mismatch_preview += ", ..."
                            warnings.warn(
                                "Provided tags are applied positionally, but TIFF metadata labels "
                                f"disagree at {len(mismatches)} channel(s). "
                                f"Examples: {mismatch_preview}",
                                stacklevel=2,
                            )
                elif labels is not None:
                    # Match provided tags against metadata labels by canonical name
                    # so fluorophore names and construct tags can be mixed.
                    desired_tokens = {_channel_match_token(tag) for tag in tags}
                    matching_labels = np.array(
                        [_channel_match_token(lbl) in desired_tokens for lbl in labels],
                        dtype=bool,
                    )
                    if np.any(matching_labels):
                        print(
                            f"Labels that are found in the image but skipped: {np.array(labels)[~matching_labels]}"
                        )
                        img = img[:, matching_labels]
                        channel_names = [
                            label for label, keep in zip(labels, matching_labels) if keep
                        ]
                    else:
                        raise AssertionError(
                            "Provided tags do not match any labels found in TIFF metadata."
                        )
                else:
                    # No labels to match against: assume provided names describe the first N channels.
                    img = img[:, : len(tags), ...]
                    channel_names = tags
            elif labels is not None:
                channel_names = labels
            else:
                channel_names = [f"channel_{i + 1}" for i in range(n_channels)]

        if channel_names is not None:
            order, _ = set_order(channel_names, include_nontags, mode=order_mode)
            if len(order) == 0:
                raise ValueError(
                    "No channels remain after ordering/filtering. "
                    "Check tag names and `include_nontags`."
                )
            img = np.take(img, order, axis=1)

        if img.shape[0] > 1:
            print("Shape detected as 3D.")
            return img.transpose(1, 0, 2, 3)  # zcyx -> czyx
        else:
            return img[0]
    except Exception as e:
        print(f"Error reading TIFF file: {e}")
        return None


def set_order(tags, include: bool = True, mode: str = "construct"):
    if mode == "provided":
        return list(range(len(tags))), None
    if mode == "fluorophore":
        mode = "construct"
    if mode != "construct":
        raise ValueError(f"Unknown set_order mode '{mode}'.")

    tags = list(tags)
    matches = {construct: [] for construct in CONSTRUCT_CHANNEL_ORDER}
    nontags = []

    for i, tag in enumerate(tags):
        canonical = _canonical_construct_channel(tag)
        if canonical in matches:
            matches[canonical].append(i)
        else:
            nontags.append(i)

    order = []
    for construct in CONSTRUCT_CHANNEL_ORDER:
        order.extend(matches[construct])

    if include:
        order.extend(nontags)

    return order, None


def relabel_masks(masks, labels):
    """
    Relabel the cell_data based on labels.

    Args:
        masks (np.ndarray): The original mask array.
        labels (np.ndarray): The labels for each mask.

    Returns:
        np.ndarray: The relabeled cell_data.
    """
    # Replace pandas.NA with a placeholder, such as -1 or None, depending on your use case
    labels = pd.Series(labels).fillna(-1).values

    labeled_masks = np.zeros_like(masks)

    for i, unique_label in enumerate(np.unique(labels)):
        if unique_label == -1:
            continue  # Skip unassigned labels (previously NA)
        masks_with_this_label = np.where(labels == unique_label)[0] + 1
        masks_this_label = np.isin(masks, masks_with_this_label)
        labeled_masks[masks_this_label] = i + 1

    return labeled_masks


def plot_masks(cell_data, color_by="barcode"):
    """
    Plot the cell_data with colors based on barcodes or clusters.

    Args:
        cell_data (CellData): The CellData object containing mask and properties information.
        color_by (str): The attribute to color the cell_data by ('barcode' or 'cluster').
    """
    if color_by not in ["barcode", "cluster"]:
        raise ValueError("color_by must be 'barcode' or 'cluster'")

    # Extract the relevant labels from the properties DataFrame
    if color_by == "barcode":
        barcode_strings = cell_data.properties["barcode_string"].values
        unique_barcodes, labels = np.unique(barcode_strings, return_inverse=True)

    elif color_by == "cluster":
        labels = cell_data.properties["cluster"].values

    # Relabel the cell_data
    labeled_masks = relabel_masks(cell_data.masks, labels)

    unique_labels = np.unique(labels) + 1

    # Create Glasbey palette
    gb = glasbey.create_palette(len(unique_labels) + 1)
    gb[0] = "#000000"  # Set first item to black

    if color_by == "barcode":
        # Check if there is a barcode that is all negative (all '-' characters)
        if hasattr(cell_data, "null_barcode"):
            gb[1] = (
                "#808080"  # Set second item to gray if there is an all-negative barcode
            )

    cmap = mcolors.ListedColormap(gb)  # To colormap

    # Create a normalization instance with correct boundaries
    norm = mcolors.BoundaryNorm(
        boundaries=np.arange(len(unique_labels) + 2) - 0.5,
        ncolors=len(unique_labels) + 1,
    )
    plt.figure()
    # Plot the image with the custom colormap
    plt.imshow(labeled_masks, cmap=cmap, norm=norm)

    # Create a colorbar with custom tick labels
    cbar = plt.colorbar(ticks=np.arange(len(unique_labels) + 1))
    if color_by == "barcode":
        labels = np.append("No cell_data", unique_barcodes)
    else:
        labels = np.append("No cell_data", unique_labels)
    cbar.ax.set_yticklabels(labels)


def generate_glasbey(iterable):
    """
    Creates a palette of Glasbey colors from any iterable. The palette runs the length of unique values in the iterable.
    """
    if isinstance(iterable, pd.Series):
        iterable = iterable.to_numpy()
    my_set = np.unique(iterable).tolist()
    gb = glasbey.create_palette(palette_size=len(my_set))
    palette = []

    for i in iterable:
        if pd.isna(i):  # Handle the fully negative barcodes
            palette.append((0, 0, 0))  # Assign black or any other color for NA values
        else:
            palette.append(gb[my_set.index(i)])

    return pd.Series(palette).to_numpy()


def histogram_correct(images: np.array, match: str = "first", n_jobs: int = -1):
    # cache image dtype
    dtype = images.dtype

    assert (
        3 <= len(images.shape) <= 4
    ), f"Expected 3d or 4d image stack, instead got {len(images.shape)} dimensions"

    avail_match_methods = ["first", "neighbor"]
    assert (
        match in avail_match_methods
    ), f"'match' expected to be one of {avail_match_methods}, instead got {match}"

    args_list = [
        (
            channel,
            match,
        )
        for channel in images
    ]

    images = Parallel(n_jobs=n_jobs)(delayed(_correct)(*args) for args in args_list)

    images = np.array(images, dtype=dtype)

    images = images.transpose(1, 0, 2, 3)  # CZYX --> ZCYX

    return images


def _correct(channel, match):

    channel = np.array(channel)
    k, m, n = channel.shape
    pixel_size = m * n

    # flatten the last dimensions and calculate normalized cdf
    channel = channel.reshape(k, -1)
    values, cdfs = [], []

    for i in range(k):

        if i > 0:
            if match == "first":
                match_ix = 0
            else:
                match_ix = i - 1

            val, ix, cnt = np.unique(
                channel[i, ...].flatten(), return_inverse=True, return_counts=True
            )
            cdf = np.cumsum(cnt) / pixel_size

            interpolated = np.interp(cdf, cdfs[match_ix], values[match_ix])
            channel[i, ...] = interpolated[ix]

        if i == 0 or match == "neighbor":
            val, cnt = np.unique(channel[i, ...].flatten(), return_counts=True)
            cdf = np.cumsum(cnt) / pixel_size
            values.append(val)
            cdfs.append(cdf)

    channel = channel.reshape(k, m, n)

    return channel


def read_metadata(file_path):

    try:
        with tifffile.TiffFile(file_path) as tif:
            metadata = tif.pages[0].tags
    except Exception as e:
        print(f"Error reading TIFF file: {e}")
        return None

    return metadata


def plot_cells_heatmap(df: pd.DataFrame, bin_size: int = 10, plot: bool = True):
    """
    Plot a binned 2D representation of a 3D dataset, where the value of the bins in XY are the sum of detected cells in
    that set of XY coordinates.

    Args:
        df: pd.DataFrame. The dataset that should contain at least a range of datapoints with each an X and Y
            coordinate.
        bin_size: int. Size of the bins in XY pixels. Bins will always be squares.
        plot: bool. Whether to plot the heatmap or not.
    Returns:
        binned_resized_arr: np.ndarray. 2D representation of XY-binned cell counts in Z. The output dimensions are the
            same as the range of data in the input DataFrame.
    """

    # Get all the XY coordinates from the DataFrame, round them and set to int (this includes XY from every Z)
    xy = df[['y', 'x']].round().astype(int).to_numpy()

    # Get unique coordinates and their counts in Z (= accumulation of cells at that XY coordinate)
    unique_coords, counts = np.unique(xy, axis=0, return_counts=True)

    # Create an empty array
    y_dim, x_dim = xy.max(axis=0) + 1
    summed_arr = np.zeros((y_dim, x_dim), dtype=int)

    # Fill the empty array with the precalculated counts
    summed_arr[unique_coords[:, 0], unique_coords[:, 1]] = counts

    # Bin the newly created array of sums
    binned_arr = block_reduce(summed_arr, block_size=bin_size, func=np.sum)

    # To scale properly back to the original image size and keep the right block sizes, we need to 'overscale'.
    # Basically, we find the number of pixels that need to be added to rescale the blocks to the correct size, then we
    # crop the image to return it to its original size.
    adj_size_pad = bin_size - np.array(summed_arr.shape) % bin_size
    adj_size = tuple(np.array(summed_arr.shape) + adj_size_pad)

    binned_resized_arr = resize(binned_arr, adj_size, order=0)
    binned_resized_arr = binned_resized_arr[:-adj_size_pad[0], :-adj_size_pad[1]]

    if plot:
        # Show figure using the Express module
        fig = px.imshow(binned_resized_arr)
        fig.show()

    return binned_resized_arr


def plot_heatmap_barcodes(xyz_df: pd.DataFrame, bc_df: pd.DataFrame, bin_size: int = 10):
    heatmap = plot_cells_heatmap(xyz_df, bin_size=bin_size, plot=False)

    # Create an empty array
    y_dim, x_dim = heatmap.shape
    summed_arr = np.zeros((2, y_dim, x_dim), dtype=int)

    bin_shape = (1, bin_size, bin_size)

    bc = bc_df['barcode_string'].unique()

    # First make an overview of barcodes in XY
    for i, code in enumerate(bc):
        df = bc_df.loc[bc_df['barcode_string'] == code]
        # Get all the XY coordinates from the DataFrame, round them and set to int (this includes XY from every Z)
        xy = df[['y', 'x']].round().astype(int).to_numpy()

        # Get unique coordinates in Z
        unique_coords = np.unique(xy, axis=0)

        # Fill the empty array with the iterator
        summed_arr[0][unique_coords[:, 0], unique_coords[:, 1]] = i+1

    # Derive clusters
    clusters = []
    for mask_nr in bc_df['mask_number'].to_numpy():
        match = xyz_df.loc[xyz_df['mask_number'] == mask_nr]
        cluster = match['cluster_volume'].astype(int).to_numpy()[0]
        clusters.append(cluster)
    unique_clusters = np.unique(clusters)

    # Make an overview of unique crypt-villus units in XY
    for i, code in enumerate(unique_clusters):
        df = xyz_df.loc[xyz_df['cluster_volume'] == code]
        # Get all the XY coordinates from the DataFrame, round them and set to int (this includes XY from every Z)
        xy = df[['y', 'x']].round().astype(int).to_numpy()

        # Get unique coordinates in Z
        unique_coords = np.unique(xy, axis=0)

        # Fill the empty array with the iterator
        summed_arr[1][unique_coords[:, 0], unique_coords[:, 1]] = i+1

    # Bin the newly created array, keep the highest value
    binned_arr = block_reduce(summed_arr, block_size=bin_shape, func=np.max)

    # To scale properly back to the original image size and keep the right block sizes, we need to 'overscale'.
    # Basically, we find the number of pixels that need to be added to rescale the blocks to the correct size, then we
    # crop the image to return it to its original size.
    adj_size_pad = bin_size - np.array(summed_arr[0].shape) % bin_size
    adj_size = (2,) + tuple(np.array(summed_arr[0].shape) + adj_size_pad)

    binned_resized_arr = resize(binned_arr, adj_size, order=0)
    binned_resized_arr = binned_resized_arr[:, :-adj_size_pad[0], :-adj_size_pad[1]]

    arr = np.concatenate([heatmap[None, ...], binned_resized_arr], axis=0)

    if arr.max() < 256:
        arr = arr.astype(np.uint8)
    elif arr.max() < 65536:
        arr = arr.astype(np.uint16)

    return arr
